/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salon;
import com.mysql.cj.protocol.Resultset;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.Calendar;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.Instant;

public class mainGUI extends javax.swing.JFrame {
    
public void date(){
    LocalDateTime now = LocalDateTime.now();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    String fDateTime = now.format(formatter);
        
}

    public mainGUI() {
        initComponents();
         
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderbtng = new javax.swing.ButtonGroup();
        servicesbtng = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        whiteBGpanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        menuLogo = new javax.swing.JLabel();
        servicesbtn = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        feedbacksbtn = new javax.swing.JButton();
        exibtn = new javax.swing.JButton();
        historybtn = new javax.swing.JButton();
        infobtn = new javax.swing.JButton();
        profilebtn = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        history1 = new javax.swing.JTabbedPane();
        hometab = new javax.swing.JPanel();
        homepageLogo = new javax.swing.JLabel();
        hptxt1 = new javax.swing.JLabel();
        hptxt2 = new javax.swing.JLabel();
        hptxt3 = new javax.swing.JLabel();
        hptxt4 = new javax.swing.JLabel();
        hptxt5 = new javax.swing.JLabel();
        hptxt6 = new javax.swing.JLabel();
        hptxt7 = new javax.swing.JLabel();
        hptxt8 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        feedbackstab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        f1 = new javax.swing.JCheckBox();
        f2 = new javax.swing.JCheckBox();
        f3 = new javax.swing.JCheckBox();
        f4 = new javax.swing.JCheckBox();
        f5 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        commentarea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        s5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        servicestab = new javax.swing.JPanel();
        serviceslbl = new javax.swing.JLabel();
        employeelbl = new javax.swing.JLabel();
        customerlbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JLabel();
        cNumber = new javax.swing.JTextField();
        customercontactnumlbl = new javax.swing.JLabel();
        cName = new javax.swing.JTextField();
        customeragelbl = new javax.swing.JLabel();
        agetxt = new javax.swing.JTextField();
        customergenderlbl = new javax.swing.JLabel();
        malerbtn = new javax.swing.JRadioButton();
        femalerbtn = new javax.swing.JRadioButton();
        rolerbtn1 = new javax.swing.JRadioButton();
        rolerbtn2 = new javax.swing.JRadioButton();
        rolerbtn3 = new javax.swing.JRadioButton();
        employeenamelbl = new javax.swing.JLabel();
        employeenamecb = new javax.swing.JComboBox<>();
        hairservicesrbtn = new javax.swing.JRadioButton();
        bodytreatservicesrbtn = new javax.swing.JRadioButton();
        nailservicesrbtn = new javax.swing.JRadioButton();
        category = new javax.swing.JComboBox<>();
        submitbtn = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        p = new javax.swing.JLabel();
        category1 = new javax.swing.JComboBox<>();
        p1 = new javax.swing.JLabel();
        price1 = new javax.swing.JTextField();
        category2 = new javax.swing.JComboBox<>();
        p2 = new javax.swing.JLabel();
        price2 = new javax.swing.JTextField();
        dt = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        history2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historytb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        whiteBGpanel.setBackground(new java.awt.Color(255, 124, 159));
        whiteBGpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(231, 182, 222));
        menuPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                menuPanelKeyReleased(evt);
            }
        });
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menuPanel.add(menuLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 19, -1, -1));

        servicesbtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        servicesbtn.setText("SERVICES");
        servicesbtn.setToolTipText("");
        servicesbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 5));
        servicesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesbtnActionPerformed(evt);
            }
        });
        menuPanel.add(servicesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 200, 38));

        homebtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        homebtn.setText("HOME");
        homebtn.setToolTipText("");
        homebtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 5));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        menuPanel.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 200, 40));

        feedbacksbtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        feedbacksbtn.setText("FEEDBACKS");
        feedbacksbtn.setToolTipText("");
        feedbacksbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 5));
        feedbacksbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbacksbtnActionPerformed(evt);
            }
        });
        menuPanel.add(feedbacksbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, 38));

        exibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitbtn.png"))); // NOI18N
        exibtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 5));
        exibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibtnActionPerformed(evt);
            }
        });
        menuPanel.add(exibtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 50, 47));

        historybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/historybtn.png"))); // NOI18N
        historybtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 5));
        historybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historybtnActionPerformed(evt);
            }
        });
        menuPanel.add(historybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 50, 47));

        infobtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        infobtn.setText("STAFF");
        infobtn.setToolTipText("");
        infobtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 5));
        infobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infobtnActionPerformed(evt);
            }
        });
        menuPanel.add(infobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 38));

        profilebtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        profilebtn.setText("PROFILE");
        profilebtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 5));
        profilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebtnActionPerformed(evt);
            }
        });
        menuPanel.add(profilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, 40));

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\JHONLEI TORRES\\Downloads\\los.jpg")); // NOI18N
        menuPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, 0, 570, 640));

        whiteBGpanel.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 630));

        hometab.setBackground(new java.awt.Color(255, 255, 255));
        hometab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homepageLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginLOGO.png"))); // NOI18N
        hometab.add(homepageLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 250, 260));

        hptxt1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        hptxt1.setText("Triple J's Salon and Spa is an oasis of relaxation and beauty, designed to");
        hometab.add(hptxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        hptxt2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        hptxt2.setText("rejuvenate the body, mind, and spirit. With a serene ambiance, elegant decor, and");
        hometab.add(hptxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        hptxt3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        hptxt3.setText("attention to detail, Triple J offers a comprehensive range of services, including ");
        hometab.add(hptxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        hptxt4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        hptxt4.setText("expert hair styling, revitalizing skin treatments, and luxurious massages. Each ");
        hometab.add(hptxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 632, -1));

        hptxt5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        hptxt5.setText("service is carefully crafted by skilled professionals to provide clients with an indul-");
        hometab.add(hptxt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        hptxt6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        hptxt6.setText("-gent, personalized experience. Using premium products and the latest in beauty,");
        hometab.add(hptxt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        hptxt7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        hptxt7.setText("technology the team at Triple J ensures that every visit leaves clients feeling");
        hometab.add(hptxt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        hptxt8.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        hptxt8.setText("refreshed, beautiful, and confident.");
        hometab.add(hptxt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Users\\JHONLEI TORRES\\Downloads\\homi.jpg")); // NOI18N
        hometab.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 650));

        history1.addTab("hometab", hometab);

        feedbackstab.setBackground(new java.awt.Color(255, 255, 255));
        feedbackstab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        feedbackstab.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 136, -1, -1));

        cname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 4));
        feedbackstab.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 131, 206, 33));

        buttonGroup2.add(f1);
        f1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f1.setText("1");
        f1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 4));
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });
        feedbackstab.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 275, -1, -1));

        buttonGroup2.add(f2);
        f2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f2.setText("2");
        f2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 4));
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });
        feedbackstab.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 275, -1, -1));

        buttonGroup2.add(f3);
        f3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f3.setText("3");
        f3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 4));
        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });
        feedbackstab.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 275, -1, -1));

        buttonGroup2.add(f4);
        f4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f4.setText("4");
        f4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 4));
        f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f4ActionPerformed(evt);
            }
        });
        feedbackstab.add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 275, -1, -1));

        buttonGroup2.add(f5);
        f5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        f5.setText("5");
        f5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 4));
        f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f5ActionPerformed(evt);
            }
        });
        feedbackstab.add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 275, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel3.setText("Ratings");
        feedbackstab.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 182, -1, 43));

        commentarea.setColumns(20);
        commentarea.setRows(5);
        commentarea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 4));
        jScrollPane2.setViewportView(commentarea);

        feedbackstab.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 418, 120));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setText("Comments");
        feedbackstab.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel6.setText("Feedbacks");
        feedbackstab.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 40, -1, -1));

        s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star_1.png"))); // NOI18N
        feedbackstab.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 231, -1, -1));

        s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star_1.png"))); // NOI18N
        feedbackstab.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 231, -1, -1));

        s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star_1.png"))); // NOI18N
        feedbackstab.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 231, -1, -1));

        s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star_1.png"))); // NOI18N
        feedbackstab.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 231, -1, -1));

        s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star_1.png"))); // NOI18N
        feedbackstab.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 231, -1, -1));

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        feedbackstab.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\JHONLEI TORRES\\Downloads\\starla.jpg")); // NOI18N
        feedbackstab.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 640));

        history1.addTab("feedbackstab", feedbackstab);

        servicestab.setBackground(new java.awt.Color(255, 255, 255));
        servicestab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serviceslbl.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        serviceslbl.setForeground(new java.awt.Color(255, 255, 255));
        serviceslbl.setText("SERVICES");
        servicestab.add(serviceslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        employeelbl.setBackground(new java.awt.Color(255, 204, 204));
        employeelbl.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        employeelbl.setForeground(new java.awt.Color(255, 255, 255));
        employeelbl.setText("EMPLOYEE ROLE\n");
        servicestab.add(employeelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        customerlbl.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        customerlbl.setForeground(new java.awt.Color(255, 255, 255));
        customerlbl.setText("CUSTOMER  INFO");
        servicestab.add(customerlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        nametxt.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        nametxt.setForeground(new java.awt.Color(255, 255, 255));
        nametxt.setText("NAME");
        nametxt.setName(""); // NOI18N
        servicestab.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        cNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 5));
        cNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNumberActionPerformed(evt);
            }
        });
        servicestab.add(cNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 182, 30));

        customercontactnumlbl.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        customercontactnumlbl.setForeground(new java.awt.Color(255, 255, 255));
        customercontactnumlbl.setText("CONTACT NUMBER");
        servicestab.add(customercontactnumlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        cName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 5));
        cName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNameActionPerformed(evt);
            }
        });
        servicestab.add(cName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 182, 30));

        customeragelbl.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        customeragelbl.setForeground(new java.awt.Color(255, 255, 255));
        customeragelbl.setText("AGE");
        servicestab.add(customeragelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        agetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 5));
        agetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agetxtActionPerformed(evt);
            }
        });
        servicestab.add(agetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 50, 30));

        customergenderlbl.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        customergenderlbl.setForeground(new java.awt.Color(255, 255, 255));
        customergenderlbl.setText("GENDER");
        servicestab.add(customergenderlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        genderbtng.add(malerbtn);
        malerbtn.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        malerbtn.setForeground(new java.awt.Color(255, 255, 255));
        malerbtn.setText("Male");
        malerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malerbtnActionPerformed(evt);
            }
        });
        servicestab.add(malerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 60, -1));

        genderbtng.add(femalerbtn);
        femalerbtn.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        femalerbtn.setForeground(new java.awt.Color(255, 255, 255));
        femalerbtn.setText("Female");
        femalerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femalerbtnActionPerformed(evt);
            }
        });
        servicestab.add(femalerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 70, -1));

        buttonGroup1.add(rolerbtn1);
        rolerbtn1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        rolerbtn1.setText("Hairstylist");
        rolerbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolerbtn1ActionPerformed(evt);
            }
        });
        servicestab.add(rolerbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 98, -1));

        buttonGroup1.add(rolerbtn2);
        rolerbtn2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        rolerbtn2.setText("Massage Therapist");
        rolerbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolerbtn2ActionPerformed(evt);
            }
        });
        servicestab.add(rolerbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        buttonGroup1.add(rolerbtn3);
        rolerbtn3.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        rolerbtn3.setText("Manicurist/Pedicurist");
        rolerbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolerbtn3ActionPerformed(evt);
            }
        });
        servicestab.add(rolerbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        employeenamelbl.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        employeenamelbl.setForeground(new java.awt.Color(255, 255, 255));
        employeenamelbl.setText("NAME");
        servicestab.add(employeenamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        employeenamecb.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        employeenamecb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        employeenamecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeenamecbActionPerformed(evt);
            }
        });
        servicestab.add(employeenamecb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, -1));

        servicesbtng.add(hairservicesrbtn);
        hairservicesrbtn.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        hairservicesrbtn.setForeground(new java.awt.Color(255, 255, 255));
        hairservicesrbtn.setText("Hair Services");
        hairservicesrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairservicesrbtnActionPerformed(evt);
            }
        });
        servicestab.add(hairservicesrbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        servicesbtng.add(bodytreatservicesrbtn);
        bodytreatservicesrbtn.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        bodytreatservicesrbtn.setForeground(new java.awt.Color(255, 255, 255));
        bodytreatservicesrbtn.setText("Body Treatment Services");
        bodytreatservicesrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodytreatservicesrbtnActionPerformed(evt);
            }
        });
        servicestab.add(bodytreatservicesrbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        servicesbtng.add(nailservicesrbtn);
        nailservicesrbtn.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        nailservicesrbtn.setForeground(new java.awt.Color(255, 255, 255));
        nailservicesrbtn.setText("Nail Services");
        nailservicesrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nailservicesrbtnActionPerformed(evt);
            }
        });
        servicestab.add(nailservicesrbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, -1, -1));

        category.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Haircut", "Special Haircut", "Classic Rebond", "Scalp Treatment", "Hair Coloring" }));
        category.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        servicestab.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 130, -1));

        submitbtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        submitbtn.setText("SUBMIT");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        servicestab.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, -1, -1));

        price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 5));
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        servicestab.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 60, 30));

        p.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        p.setForeground(new java.awt.Color(255, 255, 255));
        p.setText("Price");
        servicestab.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 50, -1));

        category1.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        category1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal Massage", "Pain Relief", "Relaxation", "Toxin removal", "Deep Tissue Massage" }));
        category1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        category1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category1ActionPerformed(evt);
            }
        });
        servicestab.add(category1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 130, -1));

        p1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        p1.setForeground(new java.awt.Color(255, 255, 255));
        p1.setText("Price");
        servicestab.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 50, -1));

        price1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 5));
        price1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price1ActionPerformed(evt);
            }
        });
        servicestab.add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 60, 30));

        category2.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        category2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic Manicure", "Gel Manicure", "Basic Pedicure", "Gel Pedicure", "Nail Extension" }));
        category2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        category2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category2ActionPerformed(evt);
            }
        });
        servicestab.add(category2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 130, -1));

        p2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        p2.setForeground(new java.awt.Color(255, 255, 255));
        p2.setText("Price");
        servicestab.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 50, -1));

        price2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 5));
        price2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price2ActionPerformed(evt);
            }
        });
        servicestab.add(price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 60, 30));

        dt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtActionPerformed(evt);
            }
        });
        servicestab.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 180, 30));

        jLabel36.setIcon(new javax.swing.ImageIcon("C:\\Users\\JHONLEI TORRES\\Downloads\\serv.jpg")); // NOI18N
        servicestab.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 670));

        history1.addTab("servicestab", servicestab);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JESSICA.jpg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, 210));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PAULA.jpg"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 250, 220));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LEAA.jpg"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 260, 210));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/YANNAH.jpg"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 260, 200));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DIVINEE.jpg"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 260, 200));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MIYAA.jpg"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 280, 200));

        jLabel18.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel18.setText("LEA");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 40, 20));

        jLabel21.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel21.setText("DIVINA");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 70, 20));

        jLabel22.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel22.setText("PAULA");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 60, 20));

        jLabel23.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel23.setText("JESSICA");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 70, 20));

        jLabel24.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel24.setText("YANNA");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 70, 20));

        jLabel25.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel25.setText("MIYA");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 50, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel15.setText("MANICURIST");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 150, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel16.setText("HAIRSTYLIST");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 150, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel19.setText("HAIRSTYLIST");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 150, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel20.setText("MASSAGE THERAPIST");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 190, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel26.setText("MASSAGE THERAPIST");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 200, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel27.setText("MANICURIST");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 150, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Users\\JHONLEI TORRES\\Downloads\\staff.jpg")); // NOI18N
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 640));

        history1.addTab("STAFF", jPanel2);

        history2.setBackground(new java.awt.Color(255, 255, 255));
        history2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        historytb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "historyID", "Role", "EmployeeName", "CustomerName", "ContactNumber", "Age", "Gender", "Services", "Category", "Price", "datetime"
            }
        ));
        jScrollPane1.setViewportView(historytb);

        history2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 740, 340));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HISTORY");
        history2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 160, 50));

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\JHONLEI TORRES\\Downloads\\hist.jpg")); // NOI18N
        history2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 890, 640));

        history1.addTab("history", history2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LEEY.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boiserr.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 121, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jes.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel17.setText("ADMIN PROFILE");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, 64));

        jLabel28.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel28.setText("NAIL DEPARTMENT");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, 43));

        jLabel29.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel29.setText("HAIR DEPARTMENT");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 389, -1, 43));

        jLabel30.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel30.setText("BODY DEPARTMENT");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 389, -1, 43));

        jLabel39.setIcon(new javax.swing.ImageIcon("C:\\Users\\JHONLEI TORRES\\Downloads\\jessenfb.png")); // NOI18N
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 130, 120));

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\JHONLEI TORRES\\Downloads\\leyfb.png")); // NOI18N
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 130, 130));

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\JHONLEI TORRES\\Downloads\\boifb.png")); // NOI18N
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 120, 120));

        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\JHONLEI TORRES\\Downloads\\homi.jpg")); // NOI18N
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 670));

        history1.addTab("PROFILE", jPanel1);

        whiteBGpanel.add(history1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, -48, -1, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whiteBGpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whiteBGpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void servicesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesbtnActionPerformed
history1.setSelectedIndex(2);
p1.setVisible(false);
category1.setVisible(false);
price1.setVisible(false);
p.setVisible(false);
category.setVisible(false);
price.setVisible(false);
p2.setVisible(false);
category2.setVisible(false);
price2.setVisible(false);
hairservicesrbtn.setVisible(false);
nailservicesrbtn.setVisible(false);
bodytreatservicesrbtn.setVisible(false);
serviceslbl.setVisible(false);

LocalDateTime now = LocalDateTime.now();
DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm a");
String fDateTime = now.format(formatter);
dt.setText(fDateTime);

historybtn.setEnabled(true);

           
    }//GEN-LAST:event_servicesbtnActionPerformed
    
    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        history1.setSelectedIndex(0);
    }//GEN-LAST:event_homebtnActionPerformed

    private void feedbacksbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbacksbtnActionPerformed
        history1.setSelectedIndex(1);
         s1.setVisible(false);
         s2.setVisible(false);
         s3.setVisible(false);
         s4.setVisible(false);
         s5.setVisible(false);
         
         

    }//GEN-LAST:event_feedbacksbtnActionPerformed

    private void exibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibtnActionPerformed
        admin ad = new admin();
        ad.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_exibtnActionPerformed

    private void historybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historybtnActionPerformed
history1.setSelectedIndex(4);
String url = "jdbc:mysql://localhost:3306/sasdb";
String user = "root";
String password = "";

Connection connection = null;
Statement stmt = null;
ResultSet rs = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    connection = DriverManager.getConnection(url, user, password);
    stmt = connection.createStatement();
    String query = "SELECT * FROM service";
    rs = stmt.executeQuery(query);

    while (rs.next()) {
        String id = String.valueOf(rs.getInt("serviceID"));
        String role = rs.getString("Role");
        String ename = rs.getString("EmployeeName");
        String cname = rs.getString("customerName");
        String cnumber = rs.getString("ContactNumber");
        String tage = rs.getString("Age");
        String tgender = rs.getString("Gender");
        String service = rs.getString("Services");
        String category = rs.getString("Category");
        String price = rs.getString("Price");
        String datetime = rs.getString("datetime");

        String[] tbdata1 = {id, role, ename, cname, cnumber, tage, tgender, service, category, price, datetime};

        boolean isDuplicate = false;
        DefaultTableModel tbModel = (DefaultTableModel) historytb.getModel();
        for (int i = 0; i < tbModel.getRowCount(); i++) {
            if (tbModel.getValueAt(i, 0).equals(id)) {
                isDuplicate = true;
                break;
            }
        }

        if (!isDuplicate) {
            SwingUtilities.invokeLater(() -> {
                tbModel.addRow(tbdata1);
                historybtn.setEnabled(false);
            });
        }     }
} catch (ClassNotFoundException | SQLException ex) {
    Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
} finally {
    try {
        if (rs != null) rs.close();
        if (stmt != null) stmt.close();
        if (connection != null) connection.close();
    } catch (SQLException ex) {
        Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    }//GEN-LAST:event_historybtnActionPerformed

    private void infobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infobtnActionPerformed
    history1.setSelectedIndex(3);

    }//GEN-LAST:event_infobtnActionPerformed

    private void price2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price2ActionPerformed

    private void category2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category2ActionPerformed
        // TODO add your handling code here:
        String prices2 = (String) category2.getSelectedItem();
        if(prices2.equals("Basic Manicure")){
            price2.setText("100");
        }else if(prices2.equals("Gel Manicure")){
            price2.setText("150");
        }else if(prices2.equals("Basic Pedicure")){
            price2.setText("200");
        }else if(prices2.equals("Gel Pedicure")){
            price2.setText("250");
        }else if(prices2.equals("Nail Extension")){
            price2.setText("300");
        }
        else {
            price2.setText("");
        }
    }//GEN-LAST:event_category2ActionPerformed

    private void price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price1ActionPerformed

    private void category1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category1ActionPerformed
        // TODO add your handling code here:
        String prices1 = (String) category1.getSelectedItem();
        if(prices1.equals("Normal Massage")){
            price1.setText("100");
        }else if(prices1.equals("Pain Relief")){
            price1.setText("150");
        }else if(prices1.equals("Relaxation")){
            price1.setText("200");
        }else if(prices1.equals("Toxin removal")){
            price1.setText("250");
        }else if(prices1.equals("Deep Tissue Massage")){
            price1.setText("300");
        }
        else {
            price1.setText("");
        }
    }//GEN-LAST:event_category1ActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:String prices = (String) category.getSelectedItem();
    }//GEN-LAST:event_priceActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        String url = "jdbc:mysql://localhost:3306/sasdb";  
String user = "root";  
String password = "";  

String role = null;
String employeeName, customerName, contactNumber, gender = null, services = null, category = null, datetime = null;
String age, prices = null;

if (rolerbtn1.isSelected()) {
    role = rolerbtn1.getText(); 
}
if (rolerbtn2.isSelected()) {
    role = rolerbtn2.getText(); 
}
if (rolerbtn3.isSelected()) {
    role = rolerbtn3.getText();  
}

if (hairservicesrbtn.isSelected()) {
    services = hairservicesrbtn.getText();
}
if (bodytreatservicesrbtn.isSelected()) {
    services = bodytreatservicesrbtn.getText();
}
if (nailservicesrbtn.isSelected()) {
    services = nailservicesrbtn.getText();
}

if (malerbtn.isSelected()) {
    gender = malerbtn.getText();
}
if (femalerbtn.isSelected()) {
    gender = femalerbtn.getText();
}

employeeName = (String) employeenamecb.getSelectedItem();
category = (String) this.category.getSelectedItem();
category = (String) this.category1.getSelectedItem();
category = (String) this.category2.getSelectedItem();
customerName = cName.getText();  
contactNumber = cNumber.getText();  
age = agetxt.getText();  

String price1Value = price.getText();
String price2Value = price1.getText();
String price3Value = price2.getText();
double parsedPrice = 0;
double parsedPrice1 = 0;
double parsedPrice2 = 0;
datetime = dt.getText(); // datetime input from user

try {
    if (!price1Value.isEmpty()) {
        parsedPrice = Double.parseDouble(price1Value);
    }
    if (!price2Value.isEmpty()) {
        parsedPrice1 = Double.parseDouble(price2Value); 
    }
    if (!price3Value.isEmpty()) {
        parsedPrice2 = Double.parseDouble(price3Value); 
    }
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(null, "Invalid price entered.", "Error", JOptionPane.ERROR_MESSAGE);
    return; 
}

if (role != null && !role.isEmpty()) {
    int parsedAge = 0;  
    try {
        parsedAge = Integer.parseInt(age);  
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Invalid age entered.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    
    // Debugging step: print the datetime value
    System.out.println("Input datetime: " + datetime);

    // Ensure the datetime is correctly formatted
    java.sql.Timestamp timestamp = null;
    try {
        // Check if the datetime string has AM/PM format and match it accordingly
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm a"); // For 12-hour format with AM/PM
        sdf.setLenient(false); // To strictly check the validity of the date
        
        Date parsedDate = sdf.parse(datetime); // Try parsing the date with AM/PM
        
        // Convert the parsed date to Timestamp
        timestamp = new java.sql.Timestamp(parsedDate.getTime());
    } catch (Exception ex) {
        // Handle invalid date format
        JOptionPane.showMessageDialog(null, "Invalid date format. Please use the format: yyyy-MM-dd hh:mm a (e.g., 2024-11-24 03:39 PM)", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String query = "INSERT INTO `service` (`Role`, `EmployeeName`, `CustomerName`, `ContactNumber`, `Age`, `Gender`, `Services`, `Category`, `Price`, `datetime`) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    Connection connection = null;
    PreparedStatement stmt = null;

    try {
        connection = DriverManager.getConnection(url, user, password);

        stmt = connection.prepareStatement(query);
        stmt.setString(1, role); 
        stmt.setString(2, employeeName);  
        stmt.setString(3, customerName);  
        stmt.setString(4, contactNumber);  
        stmt.setInt(5, parsedAge);  
        stmt.setString(6, gender);  
        stmt.setString(7, services);  
        stmt.setString(8, category);

        // Set price based on non-empty values
        if (!price1Value.isEmpty()) {
            stmt.setDouble(9, parsedPrice);  
        } else if (!price2Value.isEmpty()) {
            stmt.setDouble(9, parsedPrice1);  
        } else if (!price3Value.isEmpty()) {
            stmt.setDouble(9, parsedPrice2);  
        }

        // Set datetime
        stmt.setTimestamp(10, timestamp);

        int rowsAffected = stmt.executeUpdate();

        if (rowsAffected > 0) {
            genderbtng.clearSelection();
            buttonGroup1.clearSelection();
            buttonGroup2.clearSelection();
            servicesbtng.clearSelection();
            agetxt.setText("");
            cName.setText("");
            cNumber.setText("");
            employeenamecb.removeAllItems();
            nailservicesrbtn.setVisible(false);
            bodytreatservicesrbtn.setVisible(false);
            hairservicesrbtn.setVisible(false);
            JOptionPane.showMessageDialog(null, "Data inserted successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Data insertion failed.");
        }

    } catch (SQLException ex) {
        Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "PLEASE FILL OUT ALL THE INFORMATION NEEDED", "ERROR", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            if (stmt != null) stmt.close();
            if (connection != null) connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    }//GEN-LAST:event_submitbtnActionPerformed
    }
    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
        String prices = (String) category.getSelectedItem();
        if(prices.equals("Haircut")){
            price.setText("100");
        }else if(prices.equals("Special Haircut")){
            price.setText("150");
        }else if(prices.equals("Classic Rebond")){
            price.setText("200");
        }else if(prices.equals("Scalp Treatment")){
            price.setText("250");
        }else if(prices.equals("Hair Coloring")){
            price.setText("300");
        }
        else {
            price.setText("");
        }
    }//GEN-LAST:event_categoryActionPerformed

    private void nailservicesrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nailservicesrbtnActionPerformed
        // TODO add your handling code here:
        if(nailservicesrbtn.isSelected()){
            p2.setVisible(true);
            category2.setVisible(true);
            price2.setVisible(true);
            p.setVisible(false);
            category.setVisible(false);
            price.setVisible(false);
            p1.setVisible(false);
            category1.setVisible(false);
            price1.setVisible(false);

        }        // TOD
    }//GEN-LAST:event_nailservicesrbtnActionPerformed

    private void bodytreatservicesrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodytreatservicesrbtnActionPerformed
        if(bodytreatservicesrbtn.isSelected()){

            p.setVisible(false);
            category.setVisible(false);
            price.setVisible(false);
            p1.setVisible(true);
            category1.setVisible(true);
            price1.setVisible(true);
            p2.setVisible(false);
            category2.setVisible(false);
            price2.setVisible(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_bodytreatservicesrbtnActionPerformed

    private void hairservicesrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairservicesrbtnActionPerformed
        // TODO add your handling code here:
        if(hairservicesrbtn.isSelected()){
            p.setVisible(true);
            category.setVisible(true);
            price.setVisible(true);
            p1.setVisible(false);
            category1.setVisible(false);
            price1.setVisible(false);
            p2.setVisible(false);
            category2.setVisible(false);
            price2.setVisible(false);
        }        // TOD
    }//GEN-LAST:event_hairservicesrbtnActionPerformed

    private void employeenamecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeenamecbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeenamecbActionPerformed

    private void rolerbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolerbtn1ActionPerformed
        // TODO add your handling code here:
         employeenamecb.removeAllItems();
        employeenamecb.addItem("JESSICA");
        employeenamecb.addItem("PAULA");
       
        serviceslbl.setVisible(true);
        hairservicesrbtn.setVisible(true);
        bodytreatservicesrbtn.setVisible(false);
        nailservicesrbtn.setVisible(false);
        p1.setVisible(false);
        category1.setVisible(false);
        price1.setVisible(false);
        p2.setVisible(false);
        category2.setVisible(false);
        price2.setVisible(false);
    }//GEN-LAST:event_rolerbtn1ActionPerformed

    private void femalerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femalerbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femalerbtnActionPerformed

    private void cNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNameActionPerformed

    private void f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f5ActionPerformed
        // TODO add your handling code here:
        s5.setVisible(true);
        s2.setVisible(true);
        s1.setVisible(true);
        s3.setVisible(true);
        s4.setVisible(true);
    }//GEN-LAST:event_f5ActionPerformed

    private void f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f4ActionPerformed
        // TODO add your handling code here:
        s2.setVisible(true);
        s1.setVisible(true);
        s3.setVisible(true);
        s4.setVisible(true);
        s5.setVisible(false);
    }//GEN-LAST:event_f4ActionPerformed

    private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
        // TODO add your handling code here:
        s2.setVisible(true);
        s1.setVisible(true);
        s3.setVisible(true);
        s5.setVisible(false);
        s4.setVisible(false);
    }//GEN-LAST:event_f3ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        // TODO add your handling code here:
        s2.setVisible(true);
        s1.setVisible(true);
        s5.setVisible(false);
        s3.setVisible(false);
        s4.setVisible(false);
    }//GEN-LAST:event_f2ActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        // TODO add your handling code here:
        s1.setVisible(true);
        s2.setVisible(false);
        s5.setVisible(false);
        s3.setVisible(false);
        s4.setVisible(false);
    }//GEN-LAST:event_f1ActionPerformed

    private void profilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebtnActionPerformed
         history1.setSelectedIndex(5);
    }//GEN-LAST:event_profilebtnActionPerformed

    private void rolerbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolerbtn2ActionPerformed
        // TODO add your handling code here: serviceslbl.setVisible(true);
         employeenamecb.removeAllItems();
         employeenamecb.addItem("LEA");
        employeenamecb.addItem("YANNA");
       serviceslbl.setVisible(true);
        hairservicesrbtn.setVisible(false);
        bodytreatservicesrbtn.setVisible(true);
        nailservicesrbtn.setVisible(false);
        p2.setVisible(false);
        category2.setVisible(false);
        price2.setVisible(false);
        p.setVisible(false);
        category.setVisible(false);
        price.setVisible(false);
        
    }//GEN-LAST:event_rolerbtn2ActionPerformed

    private void rolerbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolerbtn3ActionPerformed
        // TODO add your handling code here:
         employeenamecb.removeAllItems();
         employeenamecb.addItem("MIYA");
        employeenamecb.addItem("DIVINA");
         serviceslbl.setVisible(true);
        hairservicesrbtn.setVisible(false);
        bodytreatservicesrbtn.setVisible(false);
        nailservicesrbtn.setVisible(true);
        p1.setVisible(false);
        category1.setVisible(false);
        price1.setVisible(false);
        p.setVisible(false);
        category.setVisible(false);
        price.setVisible(false);
    }//GEN-LAST:event_rolerbtn3ActionPerformed

    private void menuPanelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuPanelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPanelKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name, rate = null, comment = null;
name = cname.getText();
comment = commentarea.getText();

if (f1.isSelected()) {
    rate = f1.getText();
}
if (f2.isSelected()) {
    rate = f2.getText();
}
if (f3.isSelected()) {
    rate = f3.getText();
}
if (f4.isSelected()) {
    rate = f4.getText();
}
if (f5.isSelected()) {
    rate = f5.getText();
}

String url = "jdbc:mysql://localhost:3306/sasdb";
String user = "root";
String password = "";

String query = "INSERT INTO `feedback` (`customerName`, `rate`, `comment`) VALUES (?, ?, ?)";

Connection connection = null;
PreparedStatement stmt = null;

try {
    connection = DriverManager.getConnection(url, user, password);
    stmt = connection.prepareStatement(query);

    stmt.setString(1, name);
    stmt.setString(2, rate);
    stmt.setString(3, comment);

    int rowsAffected = stmt.executeUpdate();

    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(null, "Data inserted successfully!");
    } else {
        JOptionPane.showMessageDialog(null, "Data insertion failed.");
    }
} catch (SQLException ex) {
    Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null, "PLEASE FILL OUT ALL THE INFORMATION NEEDED", "ERROR", JOptionPane.ERROR_MESSAGE);
} finally {
    try {
        if (stmt != null) stmt.close();
        if (connection != null) connection.close();
    } catch (SQLException ex) {
        Logger.getLogger(mainGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNumberActionPerformed

    private void agetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agetxtActionPerformed

    private void malerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malerbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_malerbtnActionPerformed

    private void dtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtActionPerformed

    }//GEN-LAST:event_dtActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agetxt;
    private javax.swing.JRadioButton bodytreatservicesrbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cName;
    private javax.swing.JTextField cNumber;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JComboBox<String> category1;
    private javax.swing.JComboBox<String> category2;
    private javax.swing.JTextField cname;
    private javax.swing.JTextArea commentarea;
    private javax.swing.JLabel customeragelbl;
    private javax.swing.JLabel customercontactnumlbl;
    private javax.swing.JLabel customergenderlbl;
    private javax.swing.JLabel customerlbl;
    private javax.swing.JTextField dt;
    private javax.swing.JLabel employeelbl;
    private javax.swing.JComboBox<String> employeenamecb;
    private javax.swing.JLabel employeenamelbl;
    private javax.swing.JButton exibtn;
    private javax.swing.JCheckBox f1;
    private javax.swing.JCheckBox f2;
    private javax.swing.JCheckBox f3;
    private javax.swing.JCheckBox f4;
    private javax.swing.JCheckBox f5;
    private javax.swing.JButton feedbacksbtn;
    private javax.swing.JPanel feedbackstab;
    private javax.swing.JRadioButton femalerbtn;
    private javax.swing.ButtonGroup genderbtng;
    private javax.swing.JRadioButton hairservicesrbtn;
    private javax.swing.JTabbedPane history1;
    private javax.swing.JPanel history2;
    private javax.swing.JButton historybtn;
    private javax.swing.JTable historytb;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel homepageLogo;
    private javax.swing.JPanel hometab;
    private javax.swing.JLabel hptxt1;
    private javax.swing.JLabel hptxt2;
    private javax.swing.JLabel hptxt3;
    private javax.swing.JLabel hptxt4;
    private javax.swing.JLabel hptxt5;
    private javax.swing.JLabel hptxt6;
    private javax.swing.JLabel hptxt7;
    private javax.swing.JLabel hptxt8;
    private javax.swing.JButton infobtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton malerbtn;
    private javax.swing.JLabel menuLogo;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JRadioButton nailservicesrbtn;
    private javax.swing.JLabel nametxt;
    private javax.swing.JLabel p;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JTextField price;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField price2;
    private javax.swing.JButton profilebtn;
    private javax.swing.JRadioButton rolerbtn1;
    private javax.swing.JRadioButton rolerbtn2;
    private javax.swing.JRadioButton rolerbtn3;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    private javax.swing.JButton servicesbtn;
    private javax.swing.ButtonGroup servicesbtng;
    private javax.swing.JLabel serviceslbl;
    private javax.swing.JPanel servicestab;
    private javax.swing.JButton submitbtn;
    private javax.swing.JPanel whiteBGpanel;
    // End of variables declaration//GEN-END:variables

    private void insertDataToMySQL() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
